# NUMPY Arrays

- Vector : 1d array
- Matrix : 2d array

In [1]:
import numpy as np

In [2]:
#ptho narray -> numpy array
list_1d = [1,2,3]
list_2d = [[1,2,3],[4,5,6],[7,8,9]]

arr_1d = np.array(list_1d)
arr_2d = np.array(list_2d)

In [4]:
#numpy array, a range(start, stop, step)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#zeros
np.zeros(3)

array([0., 0., 0.])

In [12]:
#2d, using touple of diamentions
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#retun evenly spaces number of points between 2 interals
# (start, stop, number of intervals)
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [22]:
#identity matrix, 2d square matrix, with diagonal of ones
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
#arrays of random numbers
np.random.rand(3) # 3 random numebrs betwen 0 : 1
np.random.rand(3,3) # 2d between 0 : 1

array([[0.29327009, 0.78934473, 0.35422295],
       [0.769327  , 0.41753493, 0.70765884],
       [0.27590641, 0.33181051, 0.57900341]])

In [29]:
np.random.randn(2) # from normal distribution from 01

array([-0.63300468, -0.04889196])

In [31]:
np.random.randint(1,100, 3) # (3) from low (inclusive), high (exclusive)

array([41, 64, 95])

In [33]:
np.random.choice([1,2,3],3) # random from list

array([3, 1, 1])

In [116]:
#respahe
arr = np.random.randint(0,100,25)
print(arr)

#change shape of array, if not enough items then it gives error
arr.reshape((5,5))

[50 38 23 69 63 14 56 43 63 58 48 64 69 59 44 72 62 41 86 47 81 65 44 83
 67]


array([[50, 38, 23, 69, 63],
       [14, 56, 43, 63, 58],
       [48, 64, 69, 59, 44],
       [72, 62, 41, 86, 47],
       [81, 65, 44, 83, 67]])

In [111]:
print(f"{arr.max()} @ index: {arr.argmax()}") #max and index of max, same with min

93 @ index: 13


In [118]:
arr = arr.reshape((5,5))
arr.shape

(5, 5)

In [121]:
arr.dtype #item types in array

dtype('int32')