# NUMPY Operations

- Array with Array
- Array with Scalars
- Universal Array Functions

In [2]:
import numpy as np

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#operations to functions
arr + arr
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
np.log(arr) #log the array, any invalid values will become Nan
np.sin(arr) #sin cos tan etc
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
#to put them next to each other
np.concatenate((arr,arr), axis=0) #axis denotes the dimenton

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])