# NUMPY Indexing and Selection

In [1]:
import numpy as np

In [14]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
# in numpy you can cast a slice to a number
arr[2:-1] = 100
arr

array([ 10,  11, 100, 100, 100, 100, 100, 100, 100, 100,  20])

In [23]:
arr = np.arange(10,21)

#when changing a slice, it changes the main array also, it doesnt copy
slice_ar = arr[0:5]
slice_ar[:] = 1000
arr

array([1000, 1000, 1000, 1000, 1000,   15,   16,   17,   18,   19,   20])

In [28]:
# if you want to specifically COPY
copy_arr = arr.copy()
copy_arr[:] = 0
copy_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
#inedxig 2D array
arr_2d = np.random.randint(10,20, size=(3,3))
arr_2d

array([[13, 18, 13],
       [19, 10, 11],
       [13, 17, 14]])

In [33]:
#2 ways to acess a specific index in 2d array, 2nd num in 3rd column
arr_2d[2][1]
arr_2d[2,1]

17

In [34]:
#arr[row operation, coloperation]
slice_2d = arr_2d[:2,1:] # 0,1 row, and 2,3 column
slice_2d

array([[18, 13],
       [10, 11]])

In [48]:
#conditional selection
arr[arr>5]

array([ 6,  7,  8,  9, 10])